/-
  Auto-generated by haxpipeT --emit-certified (typed extraction pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import SSProve.Hax.Runtime
import SSProve.Hax.AST
import SSProve.Hax.Semantics

set_option linter.unusedVariables false

namespace Schnorr

open SSProve.Hax

/-- Struct constructor + projections (auto-generated from Rust struct). -/
def SchnorrSignature (r : Array (Int)) (s : Array (Int)) : Array (Int) × Array (Int) := (r, s)

def «.r» (x : Array (Int) × Array (Int)) := x.1

def «.s» (x : Array (Int) × Array (Int)) := x.2

/-- External dependencies for Schnorr extraction (auto-generated). -/
class SchnorrDeps where
  group_mul (a : Array (Int)) (b : Array (Int)) : Array (Int)
  generator : Array (Int)
  hash_challenge (a : Array (Int)) (b : Array (Int)) (c : Array (Int)) : Array (Int)
  scalar_mul (a : Array (Int)) (b : Array (Int)) : Array (Int)
  scalar_add (a : Array (Int)) (b : Array (Int)) : Array (Int)
  group_add (a : Array (Int)) (b : Array (Int)) : Array (Int)

export SchnorrDeps (group_mul generator hash_challenge scalar_mul scalar_add group_add)

variable [SchnorrDeps]


mutual

def ZERO_SCALAR :=
Hax.repeat_ (0 : Int) (32 : Int)

def ZERO_POINT :=
Hax.repeat_ (0 : Int) (32 : Int)

def ZERO_SIGNATURE :=
SchnorrSignature ZERO_POINT ZERO_SCALAR

def scalar_eq (a : Array (Int)) (b : Array (Int)) :=
  let «eq» := true
  let i := (0 : Int)
  let _wf := Hax.whileFold («eq», i) (fun _ => true) fun («eq», i) =>
    if Hax.lt i (32 : Int) then
      let «eq» := if Hax.bne (Hax.index a i) (Hax.index b i) then false else «eq»
      let i := Hax.add i (1 : Int)
      Hax.cfContinue («eq», i)
    else
      Hax.cfBreak («eq», i)
  let («eq», i) := _wf.merge
  «eq»

def point_eq (a : Array (Int)) (b : Array (Int)) :=
  let «eq» := true
  let i := (0 : Int)
  let _wf := Hax.whileFold («eq», i) (fun _ => true) fun («eq», i) =>
    if Hax.lt i (32 : Int) then
      let «eq» := if Hax.bne (Hax.index a i) (Hax.index b i) then false else «eq»
      let i := Hax.add i (1 : Int)
      Hax.cfContinue («eq», i)
    else
      Hax.cfBreak («eq», i)
  let («eq», i) := _wf.merge
  «eq»

def keygen (sk : Array (Int)) :=
  let pk := group_mul sk (generator)
  (sk, pk)

def sign (sk : Array (Int)) (k : Array (Int)) (msg : Array (Int)) :=
  let pk := (keygen sk).2
  let r := group_mul k (generator)
  let c := hash_challenge r pk msg
  let c_sk := scalar_mul c sk
  let s := scalar_add k c_sk
  SchnorrSignature r s

def verify (pk : Array (Int)) (msg : Array (Int)) (sig : Array (Int) × Array (Int)) :=
  let c := hash_challenge («.r» sig) pk msg
  let lhs := group_mul («.s» sig) (generator)
  let c_pk := group_mul c pk
  let rhs := group_add («.r» sig) c_pk
  point_eq lhs rhs

def ZERO_SCALAR_impExpr : SSProve.Hax.ImpExpr :=
  (.app "repeat" [(.lit (ImpLit.int 0)), (.lit (ImpLit.int 32))])

def ZERO_POINT_impExpr : SSProve.Hax.ImpExpr :=
  (.app "repeat" [(.lit (ImpLit.int 0)), (.lit (ImpLit.int 32))])

def ZERO_SIGNATURE_impExpr : SSProve.Hax.ImpExpr :=
  (.app "SchnorrSignature" [(.var "ZERO_POINT"), (.var "ZERO_SCALAR")])

def scalar_eq_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "eq" (.lit (ImpLit.bool true)) (.letBind "i" (.lit (ImpLit.int 0)) (.seq (.whileFold (.lit (ImpLit.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (ImpLit.int 32))]) (.seq (.ifThenElse (.app "Ne" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])]) (.seq (.seq (.letBind "eq" (.lit (ImpLit.bool false)) (.var "eq")) .unitVal) .unitVal) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (ImpLit.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "eq"))))))

def point_eq_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "eq" (.lit (ImpLit.bool true)) (.letBind "i" (.lit (ImpLit.int 0)) (.seq (.whileFold (.lit (ImpLit.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (ImpLit.int 32))]) (.seq (.ifThenElse (.app "Ne" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])]) (.seq (.seq (.letBind "eq" (.lit (ImpLit.bool false)) (.var "eq")) .unitVal) .unitVal) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (ImpLit.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "eq"))))))

def keygen_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "sk" (.var "sk") (.letBind "pk" (.app "group_mul" [(.var "sk"), (.app "generator" [])]) (.tuple [(.var "sk"), (.var "pk")])))

def sign_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "sk" (.var "sk") (.letBind "k" (.var "k") (.letBind "msg" (.var "msg") (.letBind "_tup" (.app "keygen" [(.var "sk")]) (.letBind "_" (.proj (.var "_tup") 0) (.letBind "pk" (.proj (.var "_tup") 1) (.letBind "r" (.app "group_mul" [(.var "k"), (.app "generator" [])]) (.letBind "c" (.app "hash_challenge" [(.var "r"), (.var "pk"), (.var "msg")]) (.letBind "c_sk" (.app "scalar_mul" [(.var "c"), (.var "sk")]) (.letBind "s" (.app "scalar_add" [(.var "k"), (.var "c_sk")]) (.app "SchnorrSignature" [(.var "r"), (.var "s")])))))))))))

def verify_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "pk" (.var "pk") (.letBind "msg" (.var "msg") (.letBind "sig" (.var "sig") (.letBind "c" (.app "hash_challenge" [(.app ".r" [(.var "sig")]), (.var "pk"), (.var "msg")]) (.letBind "lhs" (.app "group_mul" [(.app ".s" [(.var "sig")]), (.app "generator" [])]) (.letBind "c_pk" (.app "group_mul" [(.var "c"), (.var "pk")]) (.letBind "rhs" (.app "group_add" [(.app ".r" [(.var "sig")]), (.var "c_pk")]) (.app "point_eq" [(.var "lhs"), (.var "rhs")]))))))))

end

end Schnorr

