/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import Hax.Runtime
import Hax.AST
import Hax.Semantics

set_option linter.unusedVariables false

namespace Hmac-hkdf

open Hax

mutual

def concat_64_32 «prefix» suffix :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (out, i) (fun _ => true) fun (out, i) =>
  if Hax.lt i (64 : Int) then
    let out := Hax.array_update out i (Hax.index «prefix» i)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (out, i)
else
  ControlFlow.Break (out, i)
  let (out, i) := _wf.merge
  let j := (0 : Int)
  let _wf := Hax.whileFold (out, j) (fun _ => true) fun (out, j) =>
  if Hax.lt j (32 : Int) then
    let out := Hax.array_update out (Hax.add (64 : Int) j) (Hax.index suffix j)
  let j := Hax.add j (1 : Int)
ControlFlow.Continue (out, j)
else
  ControlFlow.Break (out, j)
  let (out, j) := _wf.merge
out

def IPAD :=
(54 : Int)

def OPAD :=
(92 : Int)

def pad_key key :=
  let padded := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (padded, i) (fun _ => true) fun (padded, i) =>
  if Hax.lt i (32 : Int) then
    let padded := Hax.array_update padded i (Hax.index key i)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (padded, i)
else
  ControlFlow.Break (padded, i)
  let (padded, i) := _wf.merge
padded

def xor_block block pad :=
  let result := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (result, i) (fun _ => true) fun (result, i) =>
  if Hax.lt i (64 : Int) then
    let result := Hax.array_update result i (Hax.bitxor (Hax.index block i) pad)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (result, i)
else
  ControlFlow.Break (result, i)
  let (result, i) := _wf.merge
result

def hmac h key message :=
  let k_padded := pad_key key
  let k_ipad := xor_block k_padded IPAD
  let inner_input := concat_64_32 k_ipad message
  let inner_hash := hash_96 h inner_input
  let k_opad := xor_block k_padded OPAD
  let outer_input := concat_64_32 k_opad inner_hash
hash_96 h outer_input

def hkdf_extract h salt ikm :=
hmac h salt ikm

def hkdf_expand h prk info okm :=
  let msg := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (msg, i) (fun _ => true) fun (msg, i) =>
  if Hax.lt i (31 : Int) then
    let msg := Hax.array_update msg i (Hax.index info i)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (msg, i)
else
  ControlFlow.Break (msg, i)
  let (msg, i) := _wf.merge
  let msg := Hax.array_update msg (31 : Int) (1 : Int)
  let t1 := hmac h prk msg
  let j := (0 : Int)
  Hax.whileFold (okm, j) (fun _ => true) fun (okm, j) =>
    if Hax.lt j (32 : Int) then
    let okm := Hax.array_update okm j (Hax.index t1 j)
  let j := Hax.add j (1 : Int)
ControlFlow.Continue (okm, j)
else
  ControlFlow.Break (okm, j)

end

def concat_64_32_impExpr : Hax.ImpExpr :=
  (.letBind "prefix" (.var "prefix") (.letBind "suffix" (.var "suffix") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 64))]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "i"), (.app "index" [(.var "prefix"), (.var "i")])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.letBind "j" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "j"), (.lit (.int 32))]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.app "Add" [(.lit (.int 64)), (.var "j")]), (.app "index" [(.var "suffix"), (.var "j")])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "j" (.app "Add" [(.var "j"), (.lit (.int 1))]) (.var "j")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "out"))))))))

def IPAD_impExpr : Hax.ImpExpr :=
  (.lit (.int 54))

def OPAD_impExpr : Hax.ImpExpr :=
  (.lit (.int 92))

def pad_key_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "padded" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.seq (.letBind "padded" (.app "array_update" [(.var "padded"), (.var "i"), (.app "index" [(.var "key"), (.var "i")])]) (.var "padded")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "padded")))))

def xor_block_impExpr : Hax.ImpExpr :=
  (.letBind "block" (.var "block") (.letBind "pad" (.var "pad") (.letBind "result" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 64))]) (.seq (.seq (.letBind "result" (.app "array_update" [(.var "result"), (.var "i"), (.app "BitXor" [(.app "index" [(.var "block"), (.var "i")]), (.var "pad")])]) (.var "result")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "result"))))))

def hmac_impExpr : Hax.ImpExpr :=
  (.letBind "h" (.var "h") (.letBind "key" (.var "key") (.letBind "message" (.var "message") (.letBind "k_padded" (.app "pad_key" [(.var "key")]) (.letBind "k_ipad" (.app "xor_block" [(.var "k_padded"), (.var "IPAD")]) (.letBind "inner_input" (.app "concat_64_32" [(.var "k_ipad"), (.var "message")]) (.letBind "inner_hash" (.app "hash_96" [(.var "h"), (.var "inner_input")]) (.letBind "k_opad" (.app "xor_block" [(.var "k_padded"), (.var "OPAD")]) (.letBind "outer_input" (.app "concat_64_32" [(.var "k_opad"), (.var "inner_hash")]) (.app "hash_96" [(.var "h"), (.var "outer_input")]))))))))))

def hkdf_extract_impExpr : Hax.ImpExpr :=
  (.letBind "h" (.var "h") (.letBind "salt" (.var "salt") (.letBind "ikm" (.var "ikm") (.app "hmac" [(.var "h"), (.var "salt"), (.var "ikm")]))))

def hkdf_expand_impExpr : Hax.ImpExpr :=
  (.letBind "h" (.var "h") (.letBind "prk" (.var "prk") (.letBind "info" (.var "info") (.letBind "okm" (.var "okm") (.letBind "msg" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 31))]) (.seq (.seq (.letBind "msg" (.app "array_update" [(.var "msg"), (.var "i"), (.app "index" [(.var "info"), (.var "i")])]) (.var "msg")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.seq (.seq (.letBind "msg" (.app "array_update" [(.var "msg"), (.lit (.int 31)), (.lit (.int 1))]) (.var "msg")) .unitVal) (.letBind "t1" (.app "hmac" [(.var "h"), (.var "prk"), (.var "msg")]) (.letBind "j" (.lit (.int 0)) (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "j"), (.lit (.int 32))]) (.seq (.seq (.letBind "okm" (.app "array_update" [(.var "okm"), (.var "j"), (.app "index" [(.var "t1"), (.var "j")])]) (.var "okm")) .unitVal) (.seq (.seq (.letBind "j" (.app "Add" [(.var "j"), (.lit (.int 1))]) (.var "j")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal)))))))))))))

end Hmac-hkdf

