/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import Hax.Runtime
import Hax.AST
import Hax.Semantics

set_option linter.unusedVariables false

namespace Musig2

open Hax

mutual

def MAX_SIGNERS :=
(8 : Int)

def NUM_NONCES :=
(2 : Int)

def SCALAR_ZERO :=
Hax.repeat_ (0 : Int) (0 : Int)

def POINT_ZERO :=
Hax.repeat_ (0 : Int) (0 : Int)

def xor_32 a b :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (out, i) (fun _ => true) fun (out, i) =>
  if Hax.lt i (32 : Int) then
    let out := Hax.array_update out i (Hax.bitxor (Hax.index a i) (Hax.index b i))
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (out, i)
else
  ControlFlow.Break (out, i)
  let (out, i) := _wf.merge
out

def scalar_add a b :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let carry := (0 : Int)
  let i := (32 : Int)
  let _wf := Hax.whileFold (i, out, carry) (fun _ => true) fun (i, out, carry) =>
  if Hax.gt i (0 : Int) then
    let i := Hax.sub i (1 : Int)
  let ai := Hax.castVal (Hax.index a i)
  let bi := Hax.castVal (Hax.index b i)
  let ab := Hax.add ai bi
  let sum := Hax.add ab carry
  let out := Hax.array_update out i (Hax.castVal sum)
  let carry := Hax.shr sum (8 : Int)
ControlFlow.Continue (i, out, carry)
else
  ControlFlow.Break (i, out, carry)
  let (i, out, carry) := _wf.merge
out

def scalar_mul a b :=
xor_32 a b

def key_agg_coeff pubkeys num_signers signer_idx :=
  let agg := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold i (fun _ => true) fun i =>
  if Hax.band (Hax.lt i num_signers) (Hax.lt i MAX_SIGNERS) then
    let j := (0 : Int)
  let _wf := Hax.whileFold (agg, j) (fun _ => true) fun (agg, j) =>
  if Hax.lt j (32 : Int) then
    let agg := Hax.array_update agg j (Hax.bitxor (Hax.index agg j) (Hax.index (Hax.index pubkeys i) (Hax.add j (1 : Int))))
  let j := Hax.add j (1 : Int)
ControlFlow.Continue (agg, j)
else
  ControlFlow.Break (agg, j)
  let (agg, j) := _wf.merge
  let i := Hax.add i (1 : Int)
ControlFlow.Continue i
else
  ControlFlow.Break i
  let i := _wf.merge
  let j := (0 : Int)
  let _wf := Hax.whileFold (agg, j) (fun _ => true) fun (agg, j) =>
  if Hax.lt j (32 : Int) then
    let agg := Hax.array_update agg j (Hax.bitxor (Hax.index agg j) (Hax.index (Hax.index pubkeys signer_idx) (Hax.add j (1 : Int))))
  let j := Hax.add j (1 : Int)
ControlFlow.Continue (agg, j)
else
  ControlFlow.Break (agg, j)
  let (agg, j) := _wf.merge
agg

def aggregate_nonces pub_nonces num_signers _b :=
  let agg := POINT_ZERO
  let i := (0 : Int)
  let _wf := Hax.whileFold i (fun _ => true) fun i =>
  if Hax.band (Hax.lt i num_signers) (Hax.lt i MAX_SIGNERS) then
    let _let := Hax.index pub_nonces i
  let j := (0 : Int)
  let _wf := Hax.whileFold (agg, j) (fun _ => true) fun (agg, j) =>
  if Hax.lt j (33 : Int) then
    let agg := Hax.array_update agg j (Hax.bitxor (Hax.index agg j) (Hax.index r1 j))
  let j := Hax.add j (1 : Int)
ControlFlow.Continue (agg, j)
else
  ControlFlow.Break (agg, j)
  let (agg, j) := _wf.merge
  let i := Hax.add i (1 : Int)
ControlFlow.Continue i
else
  ControlFlow.Break i
  let i := _wf.merge
agg

def partial_sign nonce_secret secret_key agg_coeff challenge :=
  let a_sk := scalar_mul agg_coeff secret_key
  let a_sk_e := scalar_mul a_sk challenge
scalar_add nonce_secret a_sk_e

def aggregate_sigs partial_sigs num_signers :=
  let agg := SCALAR_ZERO
  let i := (0 : Int)
  let _wf := Hax.whileFold (agg, i) (fun _ => true) fun (agg, i) =>
  if Hax.band (Hax.lt i num_signers) (Hax.lt i MAX_SIGNERS) then
    let agg := scalar_add agg (Hax.index partial_sigs i)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (agg, i)
else
  ControlFlow.Break (agg, i)
  let (agg, i) := _wf.merge
agg

def build_signature agg_nonce agg_scalar :=
  let sig := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (sig, i) (fun _ => true) fun (sig, i) =>
  if Hax.lt i (32 : Int) then
    let sig := Hax.array_update sig i (Hax.index agg_nonce (Hax.add i (1 : Int)))
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (sig, i)
else
  ControlFlow.Break (sig, i)
  let (sig, i) := _wf.merge
  let j := (0 : Int)
  let _wf := Hax.whileFold (sig, j) (fun _ => true) fun (sig, j) =>
  if Hax.lt j (32 : Int) then
    let sig := Hax.array_update sig (Hax.add (32 : Int) j) (Hax.index agg_scalar j)
  let j := Hax.add j (1 : Int)
ControlFlow.Continue (sig, j)
else
  ControlFlow.Break (sig, j)
  let (sig, j) := _wf.merge
sig

end

def MAX_SIGNERS_impExpr : Hax.ImpExpr :=
  (.lit (.int 8))

def NUM_NONCES_impExpr : Hax.ImpExpr :=
  (.lit (.int 2))

def SCALAR_ZERO_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def POINT_ZERO_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def xor_32_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "i"), (.app "BitXor" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "out"))))))

def scalar_add_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "carry" (.lit (.int 0)) (.letBind "i" (.lit (.int 32)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Gt" [(.var "i"), (.lit (.int 0))]) (.seq (.seq (.letBind "i" (.app "Sub" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) (.letBind "ai" (.app "cast" [(.app "index" [(.var "a"), (.var "i")])]) (.letBind "bi" (.app "cast" [(.app "index" [(.var "b"), (.var "i")])]) (.letBind "ab" (.app "Add" [(.var "ai"), (.var "bi")]) (.letBind "sum" (.app "Add" [(.var "ab"), (.var "carry")]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "i"), (.app "cast" [(.var "sum")])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "carry" (.app "Shr" [(.var "sum"), (.lit (.int 8))]) (.var "carry")) .unitVal) .unitVal))))))) (.seq (.cfBreak .unitVal) .unitVal))) (.var "out")))))))

def scalar_mul_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.app "xor_32" [(.var "a"), (.var "b")])))

def key_agg_coeff_impExpr : Hax.ImpExpr :=
  (.letBind "pubkeys" (.var "pubkeys") (.letBind "num_signers" (.var "num_signers") (.letBind "signer_idx" (.var "signer_idx") (.letBind "agg" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "&&" [(.app "Lt" [(.var "i"), (.var "num_signers")]), (.app "Lt" [(.var "i"), (.var "MAX_SIGNERS")])]) (.letBind "j" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "j"), (.lit (.int 32))]) (.seq (.seq (.letBind "agg" (.app "array_update" [(.var "agg"), (.var "j"), (.app "BitXor" [(.app "index" [(.var "agg"), (.var "j")]), (.app "index" [(.app "index" [(.var "pubkeys"), (.var "i")]), (.app "Add" [(.var "j"), (.lit (.int 1))])])])]) (.var "agg")) .unitVal) (.seq (.seq (.letBind "j" (.app "Add" [(.var "j"), (.lit (.int 1))]) (.var "j")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal))) (.seq (.cfBreak .unitVal) .unitVal))) (.letBind "j" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "j"), (.lit (.int 32))]) (.seq (.seq (.letBind "agg" (.app "array_update" [(.var "agg"), (.var "j"), (.app "BitXor" [(.app "index" [(.var "agg"), (.var "j")]), (.app "index" [(.app "index" [(.var "pubkeys"), (.var "signer_idx")]), (.app "Add" [(.var "j"), (.lit (.int 1))])])])]) (.var "agg")) .unitVal) (.seq (.seq (.letBind "j" (.app "Add" [(.var "j"), (.lit (.int 1))]) (.var "j")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "agg")))))))))

def aggregate_nonces_impExpr : Hax.ImpExpr :=
  (.letBind "pub_nonces" (.var "pub_nonces") (.letBind "num_signers" (.var "num_signers") (.letBind "_b" (.var "_b") (.letBind "agg" (.var "POINT_ZERO") (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "&&" [(.app "Lt" [(.var "i"), (.var "num_signers")]), (.app "Lt" [(.var "i"), (.var "MAX_SIGNERS")])]) (.letBind "_let" (.app "index" [(.var "pub_nonces"), (.var "i")]) (.letBind "j" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "j"), (.lit (.int 33))]) (.seq (.seq (.letBind "agg" (.app "array_update" [(.var "agg"), (.var "j"), (.app "BitXor" [(.app "index" [(.var "agg"), (.var "j")]), (.app "index" [(.var "r1"), (.var "j")])])]) (.var "agg")) .unitVal) (.seq (.seq (.letBind "j" (.app "Add" [(.var "j"), (.lit (.int 1))]) (.var "j")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)))) (.seq (.cfBreak .unitVal) .unitVal))) (.var "agg")))))))

def partial_sign_impExpr : Hax.ImpExpr :=
  (.letBind "nonce_secret" (.var "nonce_secret") (.letBind "secret_key" (.var "secret_key") (.letBind "agg_coeff" (.var "agg_coeff") (.letBind "challenge" (.var "challenge") (.letBind "a_sk" (.app "scalar_mul" [(.var "agg_coeff"), (.var "secret_key")]) (.letBind "a_sk_e" (.app "scalar_mul" [(.var "a_sk"), (.var "challenge")]) (.app "scalar_add" [(.var "nonce_secret"), (.var "a_sk_e")])))))))

def aggregate_sigs_impExpr : Hax.ImpExpr :=
  (.letBind "partial_sigs" (.var "partial_sigs") (.letBind "num_signers" (.var "num_signers") (.letBind "agg" (.var "SCALAR_ZERO") (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "&&" [(.app "Lt" [(.var "i"), (.var "num_signers")]), (.app "Lt" [(.var "i"), (.var "MAX_SIGNERS")])]) (.seq (.seq (.letBind "agg" (.app "scalar_add" [(.var "agg"), (.app "index" [(.var "partial_sigs"), (.var "i")])]) (.var "agg")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "agg"))))))

def build_signature_impExpr : Hax.ImpExpr :=
  (.letBind "agg_nonce" (.var "agg_nonce") (.letBind "agg_scalar" (.var "agg_scalar") (.letBind "sig" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.seq (.letBind "sig" (.app "array_update" [(.var "sig"), (.var "i"), (.app "index" [(.var "agg_nonce"), (.app "Add" [(.var "i"), (.lit (.int 1))])])]) (.var "sig")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.letBind "j" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "j"), (.lit (.int 32))]) (.seq (.seq (.letBind "sig" (.app "array_update" [(.var "sig"), (.app "Add" [(.lit (.int 32)), (.var "j")]), (.app "index" [(.var "agg_scalar"), (.var "j")])]) (.var "sig")) .unitVal) (.seq (.seq (.letBind "j" (.app "Add" [(.var "j"), (.lit (.int 1))]) (.var "j")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "sig"))))))))

end Musig2

