/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import Hax.Runtime
import Hax.AST
import Hax.Semantics

set_option linter.unusedVariables false

namespace Simplestot

open Hax

mutual

def ZERO_SCALAR :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_POINT :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_MESSAGE :=
Hax.repeat_ (0 : Int) (0 : Int)

def xor_32 a b :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (out, i) (fun _ => true) fun (out, i) =>
  if Hax.lt i (32 : Int) then
    let out := Hax.array_update out i (Hax.bitxor (Hax.index a i) (Hax.index b i))
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (out, i)
else
  ControlFlow.Break (out, i)
  let (out, i) := _wf.merge
out

def sender_round1 a :=
pow a

def receiver_round1 a_pub b choice :=
  let g_b := pow b
  if choice then
    Hax.mul a_pub g_b
  else
    g_b

def receiver_derive_key a_pub b :=
  let shared := exp a_pub b
hash shared

def sender_encrypt a b_pub m0 m1 :=
  let a_pub := pow a
  let a_inv := inv a_pub
  let k0 := hash (exp b_pub a)
  let a_inv_b := Hax.mul a_inv b_pub
  let k1 := hash (exp a_inv_b a)
  let e0 := xor_32 m0 k0
  let e1 := xor_32 m1 k1
(e0, e1)

def receiver_decrypt key ciphertext :=
xor_32 key ciphertext

end

def ZERO_SCALAR_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_POINT_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_MESSAGE_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def xor_32_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "i"), (.app "BitXor" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "out"))))))

def sender_round1_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.app "pow" [(.var "a")]))

def receiver_round1_impExpr : Hax.ImpExpr :=
  (.letBind "a_pub" (.var "a_pub") (.letBind "b" (.var "b") (.letBind "choice" (.var "choice") (.letBind "g_b" (.app "pow" [(.var "b")]) (.ifThenElse (.var "choice") (.app "mul" [(.var "a_pub"), (.var "g_b")]) (.var "g_b"))))))

def receiver_derive_key_impExpr : Hax.ImpExpr :=
  (.letBind "a_pub" (.var "a_pub") (.letBind "b" (.var "b") (.letBind "shared" (.app "exp" [(.var "a_pub"), (.var "b")]) (.app "hash" [(.var "shared")]))))

def sender_encrypt_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b_pub" (.var "b_pub") (.letBind "m0" (.var "m0") (.letBind "m1" (.var "m1") (.letBind "a_pub" (.app "pow" [(.var "a")]) (.letBind "a_inv" (.app "inv" [(.var "a_pub")]) (.letBind "k0" (.app "hash" [(.app "exp" [(.var "b_pub"), (.var "a")])]) (.letBind "a_inv_b" (.app "mul" [(.var "a_inv"), (.var "b_pub")]) (.letBind "k1" (.app "hash" [(.app "exp" [(.var "a_inv_b"), (.var "a")])]) (.letBind "e0" (.app "xor_32" [(.var "m0"), (.var "k0")]) (.letBind "e1" (.app "xor_32" [(.var "m1"), (.var "k1")]) (.tuple [(.var "e0"), (.var "e1")]))))))))))))

def receiver_decrypt_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "ciphertext" (.var "ciphertext") (.app "xor_32" [(.var "key"), (.var "ciphertext")])))

end Simplestot

