/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import SSProve.Hax.Runtime
import SSProve.Hax.AST
import SSProve.Hax.Semantics

set_option linter.unusedVariables false

namespace Eddsa

open SSProve.Hax

mutual

def ZERO_SCALAR :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_POINT :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_SIGNATURE :=
EddsaSignature ZERO_POINT ZERO_SCALAR

def scalar_eq a b :=
  let eq := true
  let i := (0 : Int)
  let _wf := Hax.whileFold (eq, i) (fun _ => true) fun (eq, i) =>
  if Hax.lt i (32 : Int) then
    let eq := if Hax.bne (Hax.index a i) (Hax.index b i) then false else eq
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (eq, i)
else
  ControlFlow.Break (eq, i)
  let (eq, i) := _wf.merge
eq

def point_eq a b :=
  let eq := true
  let i := (0 : Int)
  let _wf := Hax.whileFold (eq, i) (fun _ => true) fun (eq, i) =>
  if Hax.lt i (32 : Int) then
    let eq := if Hax.bne (Hax.index a i) (Hax.index b i) then false else eq
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (eq, i)
else
  ControlFlow.Break (eq, i)
  let (eq, i) := _wf.merge
eq

def keygen a :=
  let pk := group_mul a (generator)
(a, pk)

def sign a k msg :=
  let _let := keygen a
  let r := group_mul k (generator)
  let c := hash_challenge r pk msg
  let c_a := scalar_mul c a
  let s := scalar_add k c_a
EddsaSignature r s

def verify pk msg sig :=
  let c := hash_challenge («.r» sig) pk msg
  let lhs := group_mul («.s» sig) (generator)
  let c_pk := group_mul c pk
  let rhs := group_add («.r» sig) c_pk
point_eq lhs rhs

end

def ZERO_SCALAR_impExpr : SSProve.Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_POINT_impExpr : SSProve.Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_SIGNATURE_impExpr : SSProve.Hax.ImpExpr :=
  (.app "EddsaSignature" [(.var "ZERO_POINT"), (.var "ZERO_SCALAR")])

def scalar_eq_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "eq" (.lit (.bool true)) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.ifThenElse (.app "Ne" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])]) (.seq (.seq (.letBind "eq" (.lit (.bool false)) (.var "eq")) .unitVal) .unitVal) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "eq"))))))

def point_eq_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "eq" (.lit (.bool true)) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.ifThenElse (.app "Ne" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])]) (.seq (.seq (.letBind "eq" (.lit (.bool false)) (.var "eq")) .unitVal) .unitVal) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "eq"))))))

def keygen_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "pk" (.app "group_mul" [(.var "a"), (.app "generator" [])]) (.tuple [(.var "a"), (.var "pk")])))

def sign_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "k" (.var "k") (.letBind "msg" (.var "msg") (.letBind "_let" (.app "keygen" [(.var "a")]) (.letBind "r" (.app "group_mul" [(.var "k"), (.app "generator" [])]) (.letBind "c" (.app "hash_challenge" [(.var "r"), (.var "pk"), (.var "msg")]) (.letBind "c_a" (.app "scalar_mul" [(.var "c"), (.var "a")]) (.letBind "s" (.app "scalar_add" [(.var "k"), (.var "c_a")]) (.app "EddsaSignature" [(.var "r"), (.var "s")])))))))))

def verify_impExpr : SSProve.Hax.ImpExpr :=
  (.letBind "pk" (.var "pk") (.letBind "msg" (.var "msg") (.letBind "sig" (.var "sig") (.letBind "c" (.app "hash_challenge" [(.app ".r" [(.var "sig")]), (.var "pk"), (.var "msg")]) (.letBind "lhs" (.app "group_mul" [(.app ".s" [(.var "sig")]), (.app "generator" [])]) (.letBind "c_pk" (.app "group_mul" [(.var "c"), (.var "pk")]) (.letBind "rhs" (.app "group_add" [(.app ".r" [(.var "sig")]), (.var "c_pk")]) (.app "point_eq" [(.var "lhs"), (.var "rhs")]))))))))

end Eddsa

