/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import Hax.Runtime
import Hax.AST
import Hax.Semantics

set_option linter.unusedVariables false

namespace Merkle

open Hax

mutual

def HASH_SIZE :=
(32 : Int)

def MAX_DEPTH :=
(8 : Int)

def DOMAIN_LEAF :=
(0 : Int)

def DOMAIN_NODE :=
(1 : Int)

def LEAF_BUF_SIZE :=
Hax.add (1 : Int) HASH_SIZE

def NODE_BUF_SIZE :=
Hax.add (1 : Int) (Hax.mul (2 : Int) HASH_SIZE)

def compress_leaf key data :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (out, i) (fun _ => true) fun (out, i) =>
  if Hax.lt i HASH_SIZE then
    let out := Hax.array_update out i (Hax.index key i)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (out, i)
else
  ControlFlow.Break (out, i)
  let (out, i) := _wf.merge
  let j := (0 : Int)
  let _wf := Hax.whileFold (out, j) (fun _ => true) fun (out, j) =>
  if Hax.lt j LEAF_BUF_SIZE then
    let idx := Hax.rem j HASH_SIZE
  let out := Hax.array_update out idx (Hax.bitxor (Hax.index out idx) (Hax.index data j))
  let next := Hax.rem (Hax.add idx (1 : Int)) HASH_SIZE
  let out := Hax.array_update out next (Hax.wrapping_add (Hax.index out next) (Hax.rotate_right (Hax.index out idx) (3 : Int)))
  let j := Hax.add j (1 : Int)
ControlFlow.Continue (out, j)
else
  ControlFlow.Break (out, j)
  let (out, j) := _wf.merge
out

def compress_node key data :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let i := (0 : Int)
  let _wf := Hax.whileFold (out, i) (fun _ => true) fun (out, i) =>
  if Hax.lt i HASH_SIZE then
    let out := Hax.array_update out i (Hax.index key i)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (out, i)
else
  ControlFlow.Break (out, i)
  let (out, i) := _wf.merge
  let j := (0 : Int)
  let _wf := Hax.whileFold (out, j) (fun _ => true) fun (out, j) =>
  if Hax.lt j NODE_BUF_SIZE then
    let idx := Hax.rem j HASH_SIZE
  let out := Hax.array_update out idx (Hax.bitxor (Hax.index out idx) (Hax.index data j))
  let next := Hax.rem (Hax.add idx (1 : Int)) HASH_SIZE
  let out := Hax.array_update out next (Hax.wrapping_add (Hax.index out next) (Hax.rotate_right (Hax.index out idx) (3 : Int)))
  let j := Hax.add j (1 : Int)
ControlFlow.Continue (out, j)
else
  ControlFlow.Break (out, j)
  let (out, j) := _wf.merge
out

def hash_leaf key leaf :=
  let buf := Hax.repeat_ (0 : Int) (0 : Int)
  let buf := Hax.array_update buf (0 : Int) DOMAIN_LEAF
  let i := (0 : Int)
  let _wf := Hax.whileFold (buf, i) (fun _ => true) fun (buf, i) =>
  if Hax.lt i HASH_SIZE then
    let buf := Hax.array_update buf (Hax.add (1 : Int) i) (Hax.index leaf i)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (buf, i)
else
  ControlFlow.Break (buf, i)
  let (buf, i) := _wf.merge
compress_leaf key buf

def hash_node key left right :=
  let buf := Hax.repeat_ (0 : Int) (0 : Int)
  let buf := Hax.array_update buf (0 : Int) DOMAIN_NODE
  let i := (0 : Int)
  let _wf := Hax.whileFold (buf, i) (fun _ => true) fun (buf, i) =>
  if Hax.lt i HASH_SIZE then
    let buf := Hax.array_update buf (Hax.add (1 : Int) i) (Hax.index left i)
  let buf := Hax.array_update buf (Hax.add (Hax.add (1 : Int) HASH_SIZE) i) (Hax.index right i)
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (buf, i)
else
  ControlFlow.Break (buf, i)
  let (buf, i) := _wf.merge
compress_node key buf

def build_tree_4 key leaves :=
  let h0 := hash_leaf key (Hax.index leaves (0 : Int))
  let h1 := hash_leaf key (Hax.index leaves (1 : Int))
  let h2 := hash_leaf key (Hax.index leaves (2 : Int))
  let h3 := hash_leaf key (Hax.index leaves (3 : Int))
  let left := hash_node key h0 h1
  let right := hash_node key h2 h3
hash_node key left right

def prove_4 key leaves index :=
  let h0 := hash_leaf key (Hax.index leaves (0 : Int))
  let h1 := hash_leaf key (Hax.index leaves (1 : Int))
  let h2 := hash_leaf key (Hax.index leaves (2 : Int))
  let h3 := hash_leaf key (Hax.index leaves (3 : Int))
  let left := hash_node key h0 h1
  let right := hash_node key h2 h3
  let proof := Hax.repeat_ (Hax.repeat_ (0 : Int) (0 : Int)) (0 : Int)
  let _ := match index with
| _ =>   let proof := Hax.array_update proof (0 : Int) h1
  let proof := Hax.array_update proof (1 : Int) right
proof
| _ =>   let proof := Hax.array_update proof (0 : Int) h0
  let proof := Hax.array_update proof (1 : Int) right
proof
| _ =>   let proof := Hax.array_update proof (0 : Int) h3
  let proof := Hax.array_update proof (1 : Int) left
proof
| _ =>   let proof := Hax.array_update proof (0 : Int) h2
  let proof := Hax.array_update proof (1 : Int) left
proof
| _ => ()
proof

def verify_proof key root leaf index proof depth :=
  let current := hash_leaf key leaf
  let idx := index
  let level := (0 : Int)
  let _wf := Hax.whileFold (current, idx, level) (fun _ => true) fun (current, idx, level) =>
  if Hax.band (Hax.lt level depth) (Hax.lt level MAX_DEPTH) then
    let _ := if Hax.beq (Hax.bitand idx (1 : Int)) (0 : Int) then
    let current := hash_node key current (Hax.index proof level)
current
else
    let current := hash_node key (Hax.index proof level) current
current
  let idx := Hax.shr idx (1 : Int)
  let level := Hax.add level (1 : Int)
ControlFlow.Continue (current, idx, level)
else
  ControlFlow.Break (current, idx, level)
  let (current, idx, level) := _wf.merge
  let eq := true
  let i := (0 : Int)
  let _wf := Hax.whileFold (eq, i) (fun _ => true) fun (eq, i) =>
  if Hax.lt i HASH_SIZE then
    let eq := if Hax.bne (Hax.index current i) (Hax.index root i) then false else eq
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (eq, i)
else
  ControlFlow.Break (eq, i)
  let (eq, i) := _wf.merge
eq

end

def HASH_SIZE_impExpr : Hax.ImpExpr :=
  (.lit (.int 32))

def MAX_DEPTH_impExpr : Hax.ImpExpr :=
  (.lit (.int 8))

def DOMAIN_LEAF_impExpr : Hax.ImpExpr :=
  (.lit (.int 0))

def DOMAIN_NODE_impExpr : Hax.ImpExpr :=
  (.lit (.int 1))

def LEAF_BUF_SIZE_impExpr : Hax.ImpExpr :=
  (.app "Add" [(.lit (.int 1)), (.var "HASH_SIZE")])

def NODE_BUF_SIZE_impExpr : Hax.ImpExpr :=
  (.app "Add" [(.lit (.int 1)), (.app "Mul" [(.lit (.int 2)), (.var "HASH_SIZE")])])

def compress_leaf_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "data" (.var "data") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.var "HASH_SIZE")]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "i"), (.app "index" [(.var "key"), (.var "i")])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.letBind "j" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "j"), (.var "LEAF_BUF_SIZE")]) (.letBind "idx" (.app "Rem" [(.var "j"), (.var "HASH_SIZE")]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "idx"), (.app "BitXor" [(.app "index" [(.var "out"), (.var "idx")]), (.app "index" [(.var "data"), (.var "j")])])]) (.var "out")) .unitVal) (.letBind "next" (.app "Rem" [(.app "Add" [(.var "idx"), (.lit (.int 1))]), (.var "HASH_SIZE")]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "next"), (.app "wrapping_add" [(.app "index" [(.var "out"), (.var "next")]), (.app "rotate_right" [(.app "index" [(.var "out"), (.var "idx")]), (.lit (.int 3))])])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "j" (.app "Add" [(.var "j"), (.lit (.int 1))]) (.var "j")) .unitVal) .unitVal))))) (.seq (.cfBreak .unitVal) .unitVal))) (.var "out"))))))))

def compress_node_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "data" (.var "data") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.var "HASH_SIZE")]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "i"), (.app "index" [(.var "key"), (.var "i")])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.letBind "j" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "j"), (.var "NODE_BUF_SIZE")]) (.letBind "idx" (.app "Rem" [(.var "j"), (.var "HASH_SIZE")]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "idx"), (.app "BitXor" [(.app "index" [(.var "out"), (.var "idx")]), (.app "index" [(.var "data"), (.var "j")])])]) (.var "out")) .unitVal) (.letBind "next" (.app "Rem" [(.app "Add" [(.var "idx"), (.lit (.int 1))]), (.var "HASH_SIZE")]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "next"), (.app "wrapping_add" [(.app "index" [(.var "out"), (.var "next")]), (.app "rotate_right" [(.app "index" [(.var "out"), (.var "idx")]), (.lit (.int 3))])])]) (.var "out")) .unitVal) (.seq (.seq (.letBind "j" (.app "Add" [(.var "j"), (.lit (.int 1))]) (.var "j")) .unitVal) .unitVal))))) (.seq (.cfBreak .unitVal) .unitVal))) (.var "out"))))))))

def hash_leaf_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "leaf" (.var "leaf") (.letBind "buf" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.seq (.seq (.letBind "buf" (.app "array_update" [(.var "buf"), (.lit (.int 0)), (.var "DOMAIN_LEAF")]) (.var "buf")) .unitVal) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.var "HASH_SIZE")]) (.seq (.seq (.letBind "buf" (.app "array_update" [(.var "buf"), (.app "Add" [(.lit (.int 1)), (.var "i")]), (.app "index" [(.var "leaf"), (.var "i")])]) (.var "buf")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.app "compress_leaf" [(.var "key"), (.var "buf")])))))))

def hash_node_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "left" (.var "left") (.letBind "right" (.var "right") (.letBind "buf" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.seq (.seq (.letBind "buf" (.app "array_update" [(.var "buf"), (.lit (.int 0)), (.var "DOMAIN_NODE")]) (.var "buf")) .unitVal) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.var "HASH_SIZE")]) (.seq (.seq (.letBind "buf" (.app "array_update" [(.var "buf"), (.app "Add" [(.lit (.int 1)), (.var "i")]), (.app "index" [(.var "left"), (.var "i")])]) (.var "buf")) .unitVal) (.seq (.seq (.letBind "buf" (.app "array_update" [(.var "buf"), (.app "Add" [(.app "Add" [(.lit (.int 1)), (.var "HASH_SIZE")]), (.var "i")]), (.app "index" [(.var "right"), (.var "i")])]) (.var "buf")) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal))) (.seq (.cfBreak .unitVal) .unitVal))) (.app "compress_node" [(.var "key"), (.var "buf")]))))))))

def build_tree_4_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "leaves" (.var "leaves") (.letBind "h0" (.app "hash_leaf" [(.var "key"), (.app "index" [(.var "leaves"), (.lit (.int 0))])]) (.letBind "h1" (.app "hash_leaf" [(.var "key"), (.app "index" [(.var "leaves"), (.lit (.int 1))])]) (.letBind "h2" (.app "hash_leaf" [(.var "key"), (.app "index" [(.var "leaves"), (.lit (.int 2))])]) (.letBind "h3" (.app "hash_leaf" [(.var "key"), (.app "index" [(.var "leaves"), (.lit (.int 3))])]) (.letBind "left" (.app "hash_node" [(.var "key"), (.var "h0"), (.var "h1")]) (.letBind "right" (.app "hash_node" [(.var "key"), (.var "h2"), (.var "h3")]) (.app "hash_node" [(.var "key"), (.var "left"), (.var "right")])))))))))

def prove_4_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "leaves" (.var "leaves") (.letBind "index" (.var "index") (.letBind "h0" (.app "hash_leaf" [(.var "key"), (.app "index" [(.var "leaves"), (.lit (.int 0))])]) (.letBind "h1" (.app "hash_leaf" [(.var "key"), (.app "index" [(.var "leaves"), (.lit (.int 1))])]) (.letBind "h2" (.app "hash_leaf" [(.var "key"), (.app "index" [(.var "leaves"), (.lit (.int 2))])]) (.letBind "h3" (.app "hash_leaf" [(.var "key"), (.app "index" [(.var "leaves"), (.lit (.int 3))])]) (.letBind "left" (.app "hash_node" [(.var "key"), (.var "h0"), (.var "h1")]) (.letBind "right" (.app "hash_node" [(.var "key"), (.var "h2"), (.var "h3")]) (.letBind "proof" (.app "repeat" [(.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]), (.lit (.int 0))]) (.seq (.match_ (.var "index") [(.wildcard, (.seq (.seq (.letBind "proof" (.app "array_update" [(.var "proof"), (.lit (.int 0)), (.var "h1")]) (.var "proof")) .unitVal) (.seq (.seq (.letBind "proof" (.app "array_update" [(.var "proof"), (.lit (.int 1)), (.var "right")]) (.var "proof")) .unitVal) .unitVal))), (.wildcard, (.seq (.seq (.letBind "proof" (.app "array_update" [(.var "proof"), (.lit (.int 0)), (.var "h0")]) (.var "proof")) .unitVal) (.seq (.seq (.letBind "proof" (.app "array_update" [(.var "proof"), (.lit (.int 1)), (.var "right")]) (.var "proof")) .unitVal) .unitVal))), (.wildcard, (.seq (.seq (.letBind "proof" (.app "array_update" [(.var "proof"), (.lit (.int 0)), (.var "h3")]) (.var "proof")) .unitVal) (.seq (.seq (.letBind "proof" (.app "array_update" [(.var "proof"), (.lit (.int 1)), (.var "left")]) (.var "proof")) .unitVal) .unitVal))), (.wildcard, (.seq (.seq (.letBind "proof" (.app "array_update" [(.var "proof"), (.lit (.int 0)), (.var "h2")]) (.var "proof")) .unitVal) (.seq (.seq (.letBind "proof" (.app "array_update" [(.var "proof"), (.lit (.int 1)), (.var "left")]) (.var "proof")) .unitVal) .unitVal))), (.wildcard, .unitVal)]) (.var "proof"))))))))))))

def verify_proof_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "root" (.var "root") (.letBind "leaf" (.var "leaf") (.letBind "index" (.var "index") (.letBind "proof" (.var "proof") (.letBind "depth" (.var "depth") (.letBind "current" (.app "hash_leaf" [(.var "key"), (.var "leaf")]) (.letBind "idx" (.var "index") (.letBind "level" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "&&" [(.app "Lt" [(.var "level"), (.var "depth")]), (.app "Lt" [(.var "level"), (.var "MAX_DEPTH")])]) (.seq (.ifThenElse (.app "Eq" [(.app "BitAnd" [(.var "idx"), (.lit (.int 1))]), (.lit (.int 0))]) (.seq (.seq (.letBind "current" (.app "hash_node" [(.var "key"), (.var "current"), (.app "index" [(.var "proof"), (.var "level")])]) (.var "current")) .unitVal) .unitVal) (.seq (.seq (.letBind "current" (.app "hash_node" [(.var "key"), (.app "index" [(.var "proof"), (.var "level")]), (.var "current")]) (.var "current")) .unitVal) .unitVal)) (.seq (.seq (.letBind "idx" (.app "Shr" [(.var "idx"), (.lit (.int 1))]) (.var "idx")) .unitVal) (.seq (.seq (.letBind "level" (.app "Add" [(.var "level"), (.lit (.int 1))]) (.var "level")) .unitVal) .unitVal))) (.seq (.cfBreak .unitVal) .unitVal))) (.letBind "eq" (.lit (.bool true)) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.var "HASH_SIZE")]) (.seq (.ifThenElse (.app "Ne" [(.app "index" [(.var "current"), (.var "i")]), (.app "index" [(.var "root"), (.var "i")])]) (.seq (.seq (.letBind "eq" (.lit (.bool false)) (.var "eq")) .unitVal) .unitVal) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "eq"))))))))))))))

end Merkle

