/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import Hax.Runtime
import Hax.AST
import Hax.Semantics

set_option linter.unusedVariables false

namespace Pre

open Hax

mutual

def ZERO_SCALAR :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_ELEM :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_MSG :=
Hax.repeat_ (0 : Int) (0 : Int)

def keygen sk :=
KeyPair sk (pow sk)

def encrypt pk m r :=
  let c1 := pow r
  let pk_r := exp pk r
  let c2 := Hax.mul m pk_r
Ciphertext c1 c2

def decrypt sk ct :=
  let c1_sk := exp («.c1» ct) sk
  let c1_sk_inv := inv c1_sk
Hax.mul («.c2» ct) c1_sk_inv

def rekeygen sk_a sk_b :=
  let sk_b_inv := scalar_inv sk_b
scalar_mul sk_a sk_b_inv

def reencrypt rk ct :=
Ciphertext (exp («.c1» ct) rk) («.c2» ct)

end

def ZERO_SCALAR_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_ELEM_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_MSG_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def keygen_impExpr : Hax.ImpExpr :=
  (.letBind "sk" (.var "sk") (.app "KeyPair" [(.var "sk"), (.app "pow" [(.var "sk")])]))

def encrypt_impExpr : Hax.ImpExpr :=
  (.letBind "pk" (.var "pk") (.letBind "m" (.var "m") (.letBind "r" (.var "r") (.letBind "c1" (.app "pow" [(.var "r")]) (.letBind "pk_r" (.app "exp" [(.var "pk"), (.var "r")]) (.letBind "c2" (.app "mul" [(.var "m"), (.var "pk_r")]) (.app "Ciphertext" [(.var "c1"), (.var "c2")])))))))

def decrypt_impExpr : Hax.ImpExpr :=
  (.letBind "sk" (.var "sk") (.letBind "ct" (.var "ct") (.letBind "c1_sk" (.app "exp" [(.app ".c1" [(.var "ct")]), (.var "sk")]) (.letBind "c1_sk_inv" (.app "inv" [(.var "c1_sk")]) (.app "mul" [(.app ".c2" [(.var "ct")]), (.var "c1_sk_inv")])))))

def rekeygen_impExpr : Hax.ImpExpr :=
  (.letBind "sk_a" (.var "sk_a") (.letBind "sk_b" (.var "sk_b") (.letBind "sk_b_inv" (.app "scalar_inv" [(.var "sk_b")]) (.app "scalar_mul" [(.var "sk_a"), (.var "sk_b_inv")]))))

def reencrypt_impExpr : Hax.ImpExpr :=
  (.letBind "rk" (.var "rk") (.letBind "ct" (.var "ct") (.app "Ciphertext" [(.app "exp" [(.app ".c1" [(.var "ct")]), (.var "rk")]), (.app ".c2" [(.var "ct")])])))

end Pre

