/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import Hax.Runtime
import Hax.AST
import Hax.Semantics

set_option linter.unusedVariables false

namespace Chaum

open Hax

mutual

def ZERO_SCALAR :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_SIGNATURE :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_BLIND_FACTOR :=
Hax.repeat_ (0 : Int) (0 : Int)

def bytes_eq a b :=
  let eq := true
  let i := (0 : Int)
  let _wf := Hax.whileFold (eq, i) (fun _ => true) fun (eq, i) =>
  if Hax.lt i (32 : Int) then
    let eq := if Hax.bne (Hax.index a i) (Hax.index b i) then false else eq
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (eq, i)
else
  ControlFlow.Break (eq, i)
  let (eq, i) := _wf.merge
eq

def blind pk msg blind_factor :=
  let r_e := mod_exp blind_factor pk
mod_mul msg r_e

def unblind blind_sig blind_factor :=
  let r_inv := mod_inv blind_factor
mod_mul blind_sig r_inv

def sign_blind sk blinded_msg :=
rsa_sign sk blinded_msg

def verify pk msg sig :=
  let recovered := rsa_verify_op pk sig
bytes_eq recovered msg

def blind_sign_unblind pk sk msg blind_factor :=
  let blinded := blind pk msg blind_factor
  let blind_sig := sign_blind sk blinded
unblind blind_sig blind_factor

end

def ZERO_SCALAR_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_SIGNATURE_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_BLIND_FACTOR_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def bytes_eq_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "eq" (.lit (.bool true)) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.ifThenElse (.app "Ne" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])]) (.seq (.seq (.letBind "eq" (.lit (.bool false)) (.var "eq")) .unitVal) .unitVal) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "eq"))))))

def blind_impExpr : Hax.ImpExpr :=
  (.letBind "pk" (.var "pk") (.letBind "msg" (.var "msg") (.letBind "blind_factor" (.var "blind_factor") (.letBind "r_e" (.app "mod_exp" [(.var "blind_factor"), (.var "pk")]) (.app "mod_mul" [(.var "msg"), (.var "r_e")])))))

def unblind_impExpr : Hax.ImpExpr :=
  (.letBind "blind_sig" (.var "blind_sig") (.letBind "blind_factor" (.var "blind_factor") (.letBind "r_inv" (.app "mod_inv" [(.var "blind_factor")]) (.app "mod_mul" [(.var "blind_sig"), (.var "r_inv")]))))

def sign_blind_impExpr : Hax.ImpExpr :=
  (.letBind "sk" (.var "sk") (.letBind "blinded_msg" (.var "blinded_msg") (.app "rsa_sign" [(.var "sk"), (.var "blinded_msg")])))

def verify_impExpr : Hax.ImpExpr :=
  (.letBind "pk" (.var "pk") (.letBind "msg" (.var "msg") (.letBind "sig" (.var "sig") (.letBind "recovered" (.app "rsa_verify_op" [(.var "pk"), (.var "sig")]) (.app "bytes_eq" [(.var "recovered"), (.var "msg")])))))

def blind_sign_unblind_impExpr : Hax.ImpExpr :=
  (.letBind "pk" (.var "pk") (.letBind "sk" (.var "sk") (.letBind "msg" (.var "msg") (.letBind "blind_factor" (.var "blind_factor") (.letBind "blinded" (.app "blind" [(.var "pk"), (.var "msg"), (.var "blind_factor")]) (.letBind "blind_sig" (.app "sign_blind" [(.var "sk"), (.var "blinded")]) (.app "unblind" [(.var "blind_sig"), (.var "blind_factor")])))))))

end Chaum

