/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import Hax.Runtime
import Hax.AST
import Hax.Semantics

set_option linter.unusedVariables false

namespace Kmac

open Hax

mutual

def byte_count x :=
  let _ := if Hax.beq x (0 : Int) then
  ControlFlow.Break (1 : Int)
else
  ()
  let n := (0 : Int)
  let _ := Hax.forFold (0 : Int) (8 : Int) () fun i _acc =>
  let shift := Hax.wrapping_mul (Hax.castVal i) (8 : Int)
if Hax.lt shift (64 : Int) then
    let shifted := Hax.shr x (Hax.castVal shift)
  if Hax.gt shifted (0 : Int) then
        let n := Hax.wrapping_add i (1 : Int)
n
  else
    ()
else
  ()
n

def left_encode x :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let n := byte_count x
  let out := Hax.array_update out (0 : Int) n
  let _ := Hax.forFold (0 : Int) (8 : Int) () fun i _acc =>
  if Hax.lt i n then
    let out_idx := Hax.castVal (Hax.wrapping_sub n i)
  let shift := Hax.wrapping_mul (Hax.castVal i) (8 : Int)
  let byte_val := if Hax.lt shift (64 : Int) then
  Hax.castVal (Hax.bitand (Hax.shr x (Hax.castVal shift)) (255 : Int))
else
  (0 : Int)
  let out := Hax.array_update out out_idx byte_val
out
else
  ()
Encoded9 out (Hax.wrapping_add (Hax.castVal n) (1 : Int))

def right_encode x :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let n := byte_count x
  let _ := Hax.forFold (0 : Int) (8 : Int) () fun i _acc =>
  if Hax.lt i n then
    let out_idx := Hax.castVal (Hax.wrapping_sub (Hax.wrapping_sub n (1 : Int)) i)
  let shift := Hax.wrapping_mul (Hax.castVal i) (8 : Int)
  let byte_val := if Hax.lt shift (64 : Int) then
  Hax.castVal (Hax.bitand (Hax.shr x (Hax.castVal shift)) (255 : Int))
else
  (0 : Int)
  let out := Hax.array_update out out_idx byte_val
out
else
  ()
  let out := Hax.array_update out (Hax.castVal n) n
Encoded9 out (Hax.wrapping_add (Hax.castVal n) (1 : Int))

def encode_string_32 s s_len :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let bit_len := Hax.wrapping_mul s_len (8 : Int)
  let le := left_encode bit_len
  let _ := Hax.forFold (0 : Int) (9 : Int) () fun i _acc =>
  if Hax.lt i («.len» le) then
    let out := Hax.array_update out i (Hax.index («.data» le) i)
out
else
  ()
  let offset := «.len» le
  let _ := Hax.forFold (0 : Int) (32 : Int) () fun j _acc =>
  if Hax.lt j s_len then
    let dst := Hax.wrapping_add offset j
  if Hax.lt dst (41 : Int) then
        let out := Hax.array_update out dst (Hax.index s j)
out
  else
    ()
else
  ()
Encoded41 out (Hax.wrapping_add offset s_len)

def bytepad x_data x_len w :=
  let out := Hax.repeat_ (0 : Int) (0 : Int)
  let le_w := left_encode w
  let _ := Hax.forFold (0 : Int) (9 : Int) () fun i _acc =>
  if Hax.lt i («.len» le_w) then
    let out := Hax.array_update out i (Hax.index («.data» le_w) i)
out
else
  ()
  let offset := «.len» le_w
  let _ := Hax.forFold (0 : Int) (41 : Int) () fun j _acc =>
  if Hax.lt j x_len then
    let dst := Hax.wrapping_add offset j
  if Hax.lt dst (168 : Int) then
        let out := Hax.array_update out dst (Hax.index x_data j)
out
  else
    ()
else
  ()
out

def kmac128_preimage key data out_bits :=
  let encoded_key := encode_string_32 key (32 : Int)
  let padded_key := bytepad («.data» encoded_key) («.len» encoded_key) (168 : Int)
  let re_l := right_encode out_bits
KmacPreimage padded_key data re_l

def kmac256_preimage key data out_bits :=
  let encoded_key := encode_string_32 key (32 : Int)
  let padded_key := bytepad («.data» encoded_key) («.len» encoded_key) (136 : Int)
  let re_l := right_encode out_bits
KmacPreimage padded_key data re_l

end

def byte_count_impExpr : Hax.ImpExpr :=
  (.letBind "x" (.var "x") (.seq (.ifThenElse (.app "Eq" [(.var "x"), (.lit (.int 0))]) (.seq (.cfBreak (.lit (.int 1))) .unitVal) .unitVal) (.letBind "n" (.lit (.int 0)) (.seq (.forFold "i" (.lit (.int 0)) (.lit (.int 8)) (.letBind "shift" (.app "wrapping_mul" [(.app "cast" [(.var "i")]), (.lit (.int 8))]) (.ifThenElse (.app "Lt" [(.var "shift"), (.lit (.int 64))]) (.letBind "shifted" (.app "Shr" [(.var "x"), (.app "cast" [(.var "shift")])]) (.ifThenElse (.app "Gt" [(.var "shifted"), (.lit (.int 0))]) (.seq (.seq (.letBind "n" (.app "wrapping_add" [(.var "i"), (.lit (.int 1))]) (.var "n")) .unitVal) .unitVal) .unitVal)) .unitVal))) (.var "n")))))

def left_encode_impExpr : Hax.ImpExpr :=
  (.letBind "x" (.var "x") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "n" (.app "byte_count" [(.var "x")]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.lit (.int 0)), (.var "n")]) (.var "out")) .unitVal) (.seq (.forFold "i" (.lit (.int 0)) (.lit (.int 8)) (.ifThenElse (.app "Lt" [(.var "i"), (.var "n")]) (.letBind "out_idx" (.app "cast" [(.app "wrapping_sub" [(.var "n"), (.var "i")])]) (.letBind "shift" (.app "wrapping_mul" [(.app "cast" [(.var "i")]), (.lit (.int 8))]) (.letBind "byte_val" (.ifThenElse (.app "Lt" [(.var "shift"), (.lit (.int 64))]) (.app "cast" [(.app "BitAnd" [(.app "Shr" [(.var "x"), (.app "cast" [(.var "shift")])]), (.lit (.int 255))])]) (.lit (.int 0))) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "out_idx"), (.var "byte_val")]) (.var "out")) .unitVal) .unitVal)))) .unitVal)) (.app "Encoded9" [(.var "out"), (.app "wrapping_add" [(.app "cast" [(.var "n")]), (.lit (.int 1))])]))))))

def right_encode_impExpr : Hax.ImpExpr :=
  (.letBind "x" (.var "x") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "n" (.app "byte_count" [(.var "x")]) (.seq (.forFold "i" (.lit (.int 0)) (.lit (.int 8)) (.ifThenElse (.app "Lt" [(.var "i"), (.var "n")]) (.letBind "out_idx" (.app "cast" [(.app "wrapping_sub" [(.app "wrapping_sub" [(.var "n"), (.lit (.int 1))]), (.var "i")])]) (.letBind "shift" (.app "wrapping_mul" [(.app "cast" [(.var "i")]), (.lit (.int 8))]) (.letBind "byte_val" (.ifThenElse (.app "Lt" [(.var "shift"), (.lit (.int 64))]) (.app "cast" [(.app "BitAnd" [(.app "Shr" [(.var "x"), (.app "cast" [(.var "shift")])]), (.lit (.int 255))])]) (.lit (.int 0))) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "out_idx"), (.var "byte_val")]) (.var "out")) .unitVal) .unitVal)))) .unitVal)) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.app "cast" [(.var "n")]), (.var "n")]) (.var "out")) .unitVal) (.app "Encoded9" [(.var "out"), (.app "wrapping_add" [(.app "cast" [(.var "n")]), (.lit (.int 1))])]))))))

def encode_string_32_impExpr : Hax.ImpExpr :=
  (.letBind "s" (.var "s") (.letBind "s_len" (.var "s_len") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "bit_len" (.app "wrapping_mul" [(.var "s_len"), (.lit (.int 8))]) (.letBind "le" (.app "left_encode" [(.var "bit_len")]) (.seq (.forFold "i" (.lit (.int 0)) (.lit (.int 9)) (.ifThenElse (.app "Lt" [(.var "i"), (.app ".len" [(.var "le")])]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "i"), (.app "index" [(.app ".data" [(.var "le")]), (.var "i")])]) (.var "out")) .unitVal) .unitVal) .unitVal)) (.letBind "offset" (.app ".len" [(.var "le")]) (.seq (.forFold "j" (.lit (.int 0)) (.lit (.int 32)) (.ifThenElse (.app "Lt" [(.var "j"), (.var "s_len")]) (.letBind "dst" (.app "wrapping_add" [(.var "offset"), (.var "j")]) (.ifThenElse (.app "Lt" [(.var "dst"), (.lit (.int 41))]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "dst"), (.app "index" [(.var "s"), (.var "j")])]) (.var "out")) .unitVal) .unitVal) .unitVal)) .unitVal)) (.app "Encoded41" [(.var "out"), (.app "wrapping_add" [(.var "offset"), (.var "s_len")])])))))))))

def bytepad_impExpr : Hax.ImpExpr :=
  (.letBind "x_data" (.var "x_data") (.letBind "x_len" (.var "x_len") (.letBind "w" (.var "w") (.letBind "out" (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))]) (.letBind "le_w" (.app "left_encode" [(.var "w")]) (.seq (.forFold "i" (.lit (.int 0)) (.lit (.int 9)) (.ifThenElse (.app "Lt" [(.var "i"), (.app ".len" [(.var "le_w")])]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "i"), (.app "index" [(.app ".data" [(.var "le_w")]), (.var "i")])]) (.var "out")) .unitVal) .unitVal) .unitVal)) (.letBind "offset" (.app ".len" [(.var "le_w")]) (.seq (.forFold "j" (.lit (.int 0)) (.lit (.int 41)) (.ifThenElse (.app "Lt" [(.var "j"), (.var "x_len")]) (.letBind "dst" (.app "wrapping_add" [(.var "offset"), (.var "j")]) (.ifThenElse (.app "Lt" [(.var "dst"), (.lit (.int 168))]) (.seq (.seq (.letBind "out" (.app "array_update" [(.var "out"), (.var "dst"), (.app "index" [(.var "x_data"), (.var "j")])]) (.var "out")) .unitVal) .unitVal) .unitVal)) .unitVal)) (.var "out")))))))))

def kmac128_preimage_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "data" (.var "data") (.letBind "out_bits" (.var "out_bits") (.letBind "encoded_key" (.app "encode_string_32" [(.var "key"), (.lit (.int 32))]) (.letBind "padded_key" (.app "bytepad" [(.app ".data" [(.var "encoded_key")]), (.app ".len" [(.var "encoded_key")]), (.lit (.int 168))]) (.letBind "re_l" (.app "right_encode" [(.var "out_bits")]) (.app "KmacPreimage" [(.var "padded_key"), (.var "data"), (.var "re_l")])))))))

def kmac256_preimage_impExpr : Hax.ImpExpr :=
  (.letBind "key" (.var "key") (.letBind "data" (.var "data") (.letBind "out_bits" (.var "out_bits") (.letBind "encoded_key" (.app "encode_string_32" [(.var "key"), (.lit (.int 32))]) (.letBind "padded_key" (.app "bytepad" [(.app ".data" [(.var "encoded_key")]), (.app ".len" [(.var "encoded_key")]), (.lit (.int 136))]) (.letBind "re_l" (.app "right_encode" [(.var "out_bits")]) (.app "KmacPreimage" [(.var "padded_key"), (.var "data"), (.var "re_l")])))))))

end Kmac

