/-
  Auto-generated by haxpipe --emit-certified (verified hax pipeline)
  Surface code + ImpExpr literals for agreement proofs.
-/
import Hax.Runtime
import Hax.AST
import Hax.Semantics

set_option linter.unusedVariables false

namespace Spake2

open Hax

mutual

def ZERO_SCALAR :=
Hax.repeat_ (0 : Int) (0 : Int)

def ZERO_POINT :=
Hax.repeat_ (0 : Int) (0 : Int)

def scalar_eq a b :=
  let eq := true
  let i := (0 : Int)
  let _wf := Hax.whileFold (eq, i) (fun _ => true) fun (eq, i) =>
  if Hax.lt i (32 : Int) then
    let eq := if Hax.bne (Hax.index a i) (Hax.index b i) then false else eq
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (eq, i)
else
  ControlFlow.Break (eq, i)
  let (eq, i) := _wf.merge
eq

def point_eq a b :=
  let eq := true
  let i := (0 : Int)
  let _wf := Hax.whileFold (eq, i) (fun _ => true) fun (eq, i) =>
  if Hax.lt i (32 : Int) then
    let eq := if Hax.bne (Hax.index a i) (Hax.index b i) then false else eq
  let i := Hax.add i (1 : Int)
ControlFlow.Continue (eq, i)
else
  ControlFlow.Break (eq, i)
  let (eq, i) := _wf.merge
eq

def client_start x w :=
  let x_g := group_mul x (generator)
  let w_m := group_mul w (m_constant)
  let t_point := group_add x_g w_m
SpakeClientMsg t_point

def server_respond y w :=
  let y_g := group_mul y (generator)
  let w_n := group_mul w (n_constant)
  let s_point := group_add y_g w_n
SpakeServerMsg s_point

def client_finish x w server_msg :=
  let w_n := group_mul w (n_constant)
  let s_minus_wn := group_sub («.s_point» server_msg) w_n
group_mul x s_minus_wn

def server_finish y w client_msg :=
  let w_m := group_mul w (m_constant)
  let t_minus_wm := group_sub («.t_point» client_msg) w_m
group_mul y t_minus_wm

def compute_key shared_point :=
hash shared_point

end

def ZERO_SCALAR_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def ZERO_POINT_impExpr : Hax.ImpExpr :=
  (.app "repeat" [(.lit (.int 0)), (.lit (.int 0))])

def scalar_eq_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "eq" (.lit (.bool true)) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.ifThenElse (.app "Ne" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])]) (.seq (.seq (.letBind "eq" (.lit (.bool false)) (.var "eq")) .unitVal) .unitVal) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "eq"))))))

def point_eq_impExpr : Hax.ImpExpr :=
  (.letBind "a" (.var "a") (.letBind "b" (.var "b") (.letBind "eq" (.lit (.bool true)) (.letBind "i" (.lit (.int 0)) (.seq (.whileFold (.lit (.bool true)) (.ifThenElse (.app "Lt" [(.var "i"), (.lit (.int 32))]) (.seq (.ifThenElse (.app "Ne" [(.app "index" [(.var "a"), (.var "i")]), (.app "index" [(.var "b"), (.var "i")])]) (.seq (.seq (.letBind "eq" (.lit (.bool false)) (.var "eq")) .unitVal) .unitVal) .unitVal) (.seq (.seq (.letBind "i" (.app "Add" [(.var "i"), (.lit (.int 1))]) (.var "i")) .unitVal) .unitVal)) (.seq (.cfBreak .unitVal) .unitVal))) (.var "eq"))))))

def client_start_impExpr : Hax.ImpExpr :=
  (.letBind "x" (.var "x") (.letBind "w" (.var "w") (.letBind "x_g" (.app "group_mul" [(.var "x"), (.app "generator" [])]) (.letBind "w_m" (.app "group_mul" [(.var "w"), (.app "m_constant" [])]) (.letBind "t_point" (.app "group_add" [(.var "x_g"), (.var "w_m")]) (.app "SpakeClientMsg" [(.var "t_point")]))))))

def server_respond_impExpr : Hax.ImpExpr :=
  (.letBind "y" (.var "y") (.letBind "w" (.var "w") (.letBind "y_g" (.app "group_mul" [(.var "y"), (.app "generator" [])]) (.letBind "w_n" (.app "group_mul" [(.var "w"), (.app "n_constant" [])]) (.letBind "s_point" (.app "group_add" [(.var "y_g"), (.var "w_n")]) (.app "SpakeServerMsg" [(.var "s_point")]))))))

def client_finish_impExpr : Hax.ImpExpr :=
  (.letBind "x" (.var "x") (.letBind "w" (.var "w") (.letBind "server_msg" (.var "server_msg") (.letBind "w_n" (.app "group_mul" [(.var "w"), (.app "n_constant" [])]) (.letBind "s_minus_wn" (.app "group_sub" [(.app ".s_point" [(.var "server_msg")]), (.var "w_n")]) (.app "group_mul" [(.var "x"), (.var "s_minus_wn")]))))))

def server_finish_impExpr : Hax.ImpExpr :=
  (.letBind "y" (.var "y") (.letBind "w" (.var "w") (.letBind "client_msg" (.var "client_msg") (.letBind "w_m" (.app "group_mul" [(.var "w"), (.app "m_constant" [])]) (.letBind "t_minus_wm" (.app "group_sub" [(.app ".t_point" [(.var "client_msg")]), (.var "w_m")]) (.app "group_mul" [(.var "y"), (.var "t_minus_wm")]))))))

def compute_key_impExpr : Hax.ImpExpr :=
  (.letBind "shared_point" (.var "shared_point") (.app "hash" [(.var "shared_point")]))

end Spake2

