#!/bin/bash
# Integration tests for haxpipeT CLI (typed pipeline).
#
# Migrated 2026-05-15 from the legacy expression-parser tests that drove
# `--run SSProve/Hax/Main.lean` (the old untyped haxpipe binary). The
# typed path requires real hax JSON, which is generated by `cargo hax
# json` from a Rust crate. If a hax_frontend_export.json fixture is
# reachable in a sibling checkout (e.g. verified-dalek), run it as the
# integration smoke test; otherwise skip that test but still verify the
# binary itself works.

set -e
PASS=0
FAIL=0
SKIP=0

HAXPIPE=".lake/build/bin/haxpipeT"

if [ ! -x "$HAXPIPE" ]; then
  echo "haxpipeT not built. Run: lake build haxpipeT" >&2
  exit 1
fi

# stack size for hax JSON parsing
ulimit -s unlimited 2>/dev/null || true

pass() { echo "PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "FAIL: $1 — $2"; FAIL=$((FAIL + 1)); }
skip() { echo "SKIP: $1 — $2"; SKIP=$((SKIP + 1)); }

echo "=== haxpipeT integration tests ==="

# Test 1: binary runs and prints help
if "$HAXPIPE" --help > /dev/null 2>&1; then
  pass "--help"
else
  fail "--help" "nonzero exit"
fi

# Test 2: invalid input is rejected with nonzero exit
if echo 'not json' | "$HAXPIPE" --emit-json 2> /dev/null; then
  fail "invalid input rejected" "exit was 0"
else
  pass "invalid input rejected"
fi

# Test 3: typed path on a real hax JSON fixture (if available)
# Look for any verified-dalek crate JSON in a sibling checkout.
JSON_FIXTURE=""
for candidate in \
    ../../verified-dalek/crates/lizard/hax_frontend_export.json \
    ../verified-dalek/crates/lizard/hax_frontend_export.json \
    ~/Claude/verified-dalek/crates/lizard/hax_frontend_export.json ; do
  if [ -f "$candidate" ]; then
    JSON_FIXTURE="$candidate"
    break
  fi
done

if [ -n "$JSON_FIXTURE" ]; then
  if "$HAXPIPE" --hax "$JSON_FIXTURE" --emit-certified --name TestLizard \
       > /tmp/haxpipeT_smoke.lean 2> /tmp/haxpipeT_smoke.err
  then
    if grep -q "namespace TestLizard" /tmp/haxpipeT_smoke.lean; then
      pass "typed path on lizard fixture"
    else
      fail "typed path on lizard fixture" "namespace missing in output"
    fi
  else
    fail "typed path on lizard fixture" "haxpipeT nonzero exit (see /tmp/haxpipeT_smoke.err)"
  fi
else
  skip "typed path on lizard fixture" "no verified-dalek checkout found"
fi

# Test 4: --emit-json mode still works on the same fixture (sanity)
if [ -n "$JSON_FIXTURE" ]; then
  if "$HAXPIPE" --hax "$JSON_FIXTURE" --emit-json --name TestLizard \
       > /tmp/haxpipeT_smoke.json 2> /dev/null
  then
    pass "--emit-json on lizard fixture"
  else
    fail "--emit-json on lizard fixture" "nonzero exit"
  fi
else
  skip "--emit-json on lizard fixture" "no verified-dalek checkout found"
fi

echo ""
echo "=== Results: $PASS passed, $FAIL failed, $SKIP skipped ==="
[ "$FAIL" -eq 0 ]
